# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :baseurl/:title/
# relative_permalinks: true

# Setup
title:               Nicholas Dechert
tagline:             'Programming, Web Development, and Information Security'
description:         'Learning by doing, and teaching along the way'
url:                 http://claymore2106.github.io
baseurl:             'http://claymore2106.github.io'
paginate:            5

# About/contact
author:
  name:              Nicholas Dechert
  url:               claymore2106.github.io
  email:             dechert.nicholas@gmail.com

# Custom vars
# version:             1.0.0
