# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Nicholas Dechert
tagline:             'Programming, Web Development, and Information Security'
description:         'Learning by doing, and teaching along the way'
url:                 https://claymore2106.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Nicholas Dechert
  url:               claymore2106.github.io
  email:             dechert.nicholas@gmail.com

# Custom vars
# version:             1.0.0
